bots:
  main:
    provider:
      name: telegram
      token: 7852198078:AAHZLvmLVhR2HdbKwxguiZ65pd_8Ck_FwmA
      mode: webhook_lambda
      debug: true
    state_repository:
              name: dynamoid
              dynamoid_config: true
              region:  'us-east-1'
              namespace: 'trackit'
              read_capacity: 3
              write_capacity: 3
  develop:
    pool_size: 1
    inline_args: true
    provider:
      name: telegram
      token: 7852198078:AAHZLvmLVhR2HdbKwxguiZ65pd_8Ck_FwmA
      debug: true
    state_repository:
              name: sequel
              endpoint: sqlite://develop.sqlite